# Copyright 2004 OTP Systems Oy. All rights reserved.

ProductID := DotTuxWS

ProductName := DotTux Workstation

Docs := DotTuxWSInstall DotTuxWS_dll

Samples := SimpleClient StringUtils SimpleAsyncClient DownloadClient SimpleEnqueuer SimpleDequeuer UnsolClient SimpleSubscriber SimpleFML32Client

CscDocFlags := /define:WSCLIENT

include ../Makefile.include
