# Copyright 2004 OTP Systems Oy. All rights reserved.

ProductID := DotTux

ProductName := DotTux

Docs := DotTuxInstall DotTux_dll DotServer

Samples := SimpleServer SimpleClient StringUtils SimpleAsyncClient ServerUtils DownloadServer DownloadClient SimpleEnqueuer SimpleDequeuer UnsolServer UnsolClient TimePublisher SimpleSubscriber SimpleFML32Server SimpleFML32Client

include ../Makefile.include
